# name: Main

on:
  push:
    branches: [main]

  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build_and_deploy:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: npm install, build - theme
      run: |
        cd themes/rosenberg-foundation
        npm ci
        gulp scss
        gulp scripts
      env:
        CI: true

    - name: Git setup
      run: |
        git config --global user.name "Github Deploy"
        git config --global user.email "j-moughon@tti.tamu.edu"
        git branch build
        git checkout build

    - name: Set WP Engine gitignore - theme
      run: |
        cd wp-content/themes/praxent
        rm .gitignore
        mv .wpegitignore .gitignore

    - name: Git commit
      run: |
        git rm -r --cached .
        git add .
        git commit -m "Build"

    - name: GitHub Action for WP Engine Git Deployment
      uses: jovrtn/github-action-wpengine-git-deploy@0.1.2
      env:
        WPENGINE_ENVIRONMENT_NAME: praxentweb
        LOCAL_BRANCH: build
        WPENGINE_SSH_KEY_PRIVATE: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }}
        WPENGINE_SSH_KEY_PUBLIC: ${{ secrets.WPENGINE_SSH_KEY_PUBLIC }}