# name: Staging

env:
  THEME_NAME: rosenberg-foundation

on:
  push:
    branches: [stg]

  pull_request:
    types: [closed]
    branches: [stg]

jobs:
  build_and_deploy:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3.0
      with:
        REMOTE_PATH: wp-content/
        CACHE_CLEAR: TRUE
        WPE_ENV: rosenbergststg
        SCROPT: import-db-stg.sh
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}