# name: Staging

env:
  THEME_NAME: rosenberg-foundation
  WPE_ENV_NAME: rosenbergstg

on:
  push:
    branches: [stg]

  pull_request:
    types: [closed]
    branches: [stg]

jobs:
  build_and_deploy:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: npm install, build - theme
      run: |
        cd themes/$THEME_NAME
        npm ci
        gulp scss
        gulp scripts
      env:
        CI: true

    - name: Git setup
      run: |
        git config --global user.name "Github Deploy"
        git config --global user.email "nando.emmanuel@gmail.com"
        git branch build
        git checkout build

    - name: Git commit
      run: |
        git rm -r --cached .
        git add .
        git commit -m "Build"

    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3.0
      env:
        WPE_ENV: $WPE_ENV_NAME
        LOCAL_BRANCH: build
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}